server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ORDER
          uri: lb://ORDER
          predicates:
            - Path=/orders/**
          filters:
            - AuthnticationFilter
            - name: CircuitBreaker
              args:
                name: ORDER
                fallbackuri: forward:/orderServiceFallBack
        - id: PRODUCT
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**
          filters:
            - AuthnticationFilter
            - name: CircuitBreaker
              args:
                name: PRODUCT
                fallbackuri: forward:/productServiceFallBack
        - id: ORDERDEATILS
          uri: lb://ORDERDEATILS
          predicates:
          -  Path=/orderdetails/**
          filters:
          - AuthnticationFilter
          - name: CircuitBreaker
            args:
              name: ORDERDEATILS
              fallbackuri: forward:/orderdetailsServiceFallBack
              
            


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost